
services:
  simba-html:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: simba-html
    networks:
      - simba-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  alpine-api:
    build:
      context: ./alpine-server
      dockerfile: Dockerfile
    container_name: alpine-api
    networks:
      - simba-network
    depends_on:
      - postgres-db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/api"] 
      interval: 10s
      timeout: 5s
      retries: 5

  nginx-proxy:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "${PROXY_PORT}:80"
    volumes:
      - ./nginx-proxy/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      simba-html:
        condition: service_healthy
      alpine-api:
        condition: service_healthy
    networks:
      - simba-network

  postgres-db:
    image: postgres:16
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - simba-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  simba-network:
    driver: bridge

