name: Build and Push Docker Image

on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: simba-html

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          load: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
        
      - name: Test container startup
        run: |
          echo "🚀 Running container for test..."
          docker run -d --name test-container -p 8080:80 ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
          sleep 5
          echo "🔍 Checking container response..."
          curl -sSf http://localhost:8080 || (docker logs test-container && exit 1)
          echo "✅ Container test passed!"
          docker rm -f test-container

      - name: Push image to Docker Hub
        uses: docker/build-push-action@v5
        with: 
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest


